name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Export Org files to HTML
        uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          export: html
          files: cv.org
          keep_files: false # Don't keep non-org files in the gh-pages branch
          branch: gh-pages # The branch to deploy to GitHub Pages
          commit_message: "Deploy: Updated CV export for GitHub Pages"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: . # Use current directory (.) since org-knit outputs files here
