name: Export CV

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Export Org files to HTML and PDF
        uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          export: html, pdf
          files: content/cv.org
          # Save exports in the 'public' folder
          keep_files: true
          commit_message: "Knit: Updated CV export"

      - name: Move exported files to public folder
        run: |
          mkdir -p public
          mv content/cv.html public/mbcv.html
          mv content/cv.pdf public/mbcv.pdf

      - name: Commit changes to public folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/
          git commit -m "Update CV HTML and PDF"
          git push
