name: Deploy CV

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Emacs environment
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox

      - name: Build the page
        run: ./build.sh

      - name: Convert HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./public/mbcv.html
          outputFile: ./public/mbcv.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
