name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure proper commit history

      - name: Export Org files to HTML
        uses: tecosaur/org-knit-action@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          export: html
          files: index.org
          keep_files: false
          branch: gh-pages
          commit_message: "Deploy: Updated CV export for GitHub Pages"

      - name: Ensure files are present for GitHub Pages
        run: ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: . # This assumes all files are in the root directory
          keep_files: true
